// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20250910150347_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The FCT",
                            Name = "Abuja"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Center of Excellence",
                            Name = "Lagos"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gateway State",
                            Name = "Ogun"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sunshine State",
                            Name = "Ondo"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fountain of Knowledge",
                            Name = "Ekiti"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.Landmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Landmarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "The presidential villa",
                            Name = "Aso Rock"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "A monument for celebrating arts and culture",
                            Name = "National Arts Theatre, Iganmu"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A historical site",
                            Name = "Freedom Park"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Description = "A stunning natural formation",
                            Name = "Idanre Hill"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Description = "A spring of warm water",
                            Name = "Ikogosi Warm Spring"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "A place of refuge for ancient Egba people.",
                            Name = "Olumo Rock"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.Landmark", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("Landmarks")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("Landmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
